const mongoose = require('mongoose');
const Medicine = require('../models/Medicine');
require('dotenv').config();

const medicines = [
  // Analgesics/Pain Relief
  {
    name: 'Paracetamol',
    genericName: 'Acetaminophen',
    category: 'Analgesic',
    type: 'Tablet',
    strength: '500mg',
    manufacturer: 'Generic Pharma',
    composition: 'Paracetamol 500mg',
    commonDosages: ['500mg', '1000mg'],
    frequencies: ['Every 4-6 hours', 'Three times daily', 'As needed'],
    timings: ['After meals', 'With meals'],
    sideEffects: ['Nausea', 'Liver damage with overdose'],
    contraindications: ['Liver disease', 'Alcohol dependence'],
    warnings: ['Do not exceed 4g per day'],
    storageInstructions: 'Store below 25°C',
    pricePerUnit: 2,
    requiresPrescription: false
  },
  {
    name: 'Ibuprofen',
    genericName: 'Ibuprofen',
    category: 'Anti-inflammatory',
    type: 'Tablet',
    strength: '400mg',
    manufacturer: 'Generic Pharma',
    composition: 'Ibuprofen 400mg',
    commonDosages: ['200mg', '400mg', '600mg'],
    frequencies: ['Three times daily', 'Every 6-8 hours'],
    timings: ['After meals'],
    sideEffects: ['Stomach upset', 'Dizziness', 'Heartburn'],
    contraindications: ['Peptic ulcer', 'Aspirin allergy', 'Kidney disease'],
    warnings: ['Take with food', 'Avoid in pregnancy'],
    storageInstructions: 'Store below 25°C',
    pricePerUnit: 3,
    requiresPrescription: false
  },
  {
    name: 'Aspirin',
    genericName: 'Acetylsalicylic acid',
    category: 'Analgesic',
    type: 'Tablet',
    strength: '75mg',
    manufacturer: 'Bayer',
    composition: 'Acetylsalicylic acid 75mg',
    commonDosages: ['75mg', '150mg', '325mg'],
    frequencies: ['Once daily', 'As needed'],
    timings: ['After breakfast'],
    sideEffects: ['Stomach bleeding', 'Tinnitus'],
    contraindications: ['Bleeding disorders', 'Peptic ulcer'],
    warnings: ['Not for children under 16'],
    storageInstructions: 'Store below 25°C',
    pricePerUnit: 1.5,
    requiresPrescription: false
  },
  {
    name: 'Diclofenac',
    genericName: 'Diclofenac sodium',
    category: 'Anti-inflammatory',
    type: 'Tablet',
    strength: '50mg',
    manufacturer: 'Novartis',
    composition: 'Diclofenac sodium 50mg',
    commonDosages: ['25mg', '50mg', '75mg'],
    frequencies: ['Twice daily', 'Three times daily'],
    timings: ['After meals'],
    sideEffects: ['GI upset', 'Headache', 'Dizziness'],
    contraindications: ['Heart failure', 'Peptic ulcer'],
    warnings: ['Cardiovascular risk'],
    storageInstructions: 'Store below 30°C',
    pricePerUnit: 4,
    requiresPrescription: true
  },

  // Antibiotics
  {
    name: 'Amoxicillin',
    genericName: 'Amoxicillin',
    category: 'Antibiotic',
    type: 'Capsule',
    strength: '500mg',
    manufacturer: 'GSK',
    composition: 'Amoxicillin trihydrate 500mg',
    commonDosages: ['250mg', '500mg'],
    frequencies: ['Three times daily', 'Every 8 hours'],
    timings: ['Before meals', 'After meals'],
    sideEffects: ['Diarrhea', 'Nausea', 'Rash'],
    contraindications: ['Penicillin allergy'],
    warnings: ['Complete full course'],
    storageInstructions: 'Store below 25°C',
    pricePerUnit: 8,
    requiresPrescription: true
  },
  {
    name: 'Azithromycin',
    genericName: 'Azithromycin',
    category: 'Antibiotic',
    type: 'Tablet',
    strength: '500mg',
    manufacturer: 'Pfizer',
    composition: 'Azithromycin dihydrate 500mg',
    commonDosages: ['250mg', '500mg'],
    frequencies: ['Once daily'],
    timings: ['Empty stomach', 'Before meals'],
    sideEffects: ['Nausea', 'Diarrhea', 'Abdominal pain'],
    contraindications: ['Macrolide allergy', 'Liver disease'],
    warnings: ['QT prolongation risk'],
    storageInstructions: 'Store below 30°C',
    pricePerUnit: 25,
    requiresPrescription: true
  },
  {
    name: 'Ciprofloxacin',
    genericName: 'Ciprofloxacin',
    category: 'Antibiotic',
    type: 'Tablet',
    strength: '500mg',
    manufacturer: 'Bayer',
    composition: 'Ciprofloxacin hydrochloride 500mg',
    commonDosages: ['250mg', '500mg', '750mg'],
    frequencies: ['Twice daily'],
    timings: ['Empty stomach'],
    sideEffects: ['Tendon problems', 'Nausea', 'Photosensitivity'],
    contraindications: ['Pregnancy', 'Children'],
    warnings: ['Avoid dairy products'],
    storageInstructions: 'Store below 25°C',
    pricePerUnit: 12,
    requiresPrescription: true
  },
  {
    name: 'Metronidazole',
    genericName: 'Metronidazole',
    category: 'Antibiotic',
    type: 'Tablet',
    strength: '400mg',
    manufacturer: 'Generic Pharma',
    composition: 'Metronidazole 400mg',
    commonDosages: ['200mg', '400mg'],
    frequencies: ['Three times daily', 'Twice daily'],
    timings: ['After meals'],
    sideEffects: ['Metallic taste', 'Nausea', 'Dark urine'],
    contraindications: ['First trimester pregnancy'],
    warnings: ['Avoid alcohol'],
    storageInstructions: 'Store below 25°C',
    pricePerUnit: 5,
    requiresPrescription: true
  },
  {
    name: 'Cefixime',
    genericName: 'Cefixime',
    category: 'Antibiotic',
    type: 'Tablet',
    strength: '200mg',
    manufacturer: 'Cipla',
    composition: 'Cefixime trihydrate 200mg',
    commonDosages: ['100mg', '200mg', '400mg'],
    frequencies: ['Once daily', 'Twice daily'],
    timings: ['With or without food'],
    sideEffects: ['Diarrhea', 'Nausea', 'Headache'],
    contraindications: ['Cephalosporin allergy'],
    warnings: ['Complete full course'],
    storageInstructions: 'Store below 25°C',
    pricePerUnit: 15,
    requiresPrescription: true
  },
  {
    name: 'Doxycycline',
    genericName: 'Doxycycline',
    category: 'Antibiotic',
    type: 'Capsule',
    strength: '100mg',
    manufacturer: 'Pfizer',
    composition: 'Doxycycline hyclate 100mg',
    commonDosages: ['50mg', '100mg'],
    frequencies: ['Once daily', 'Twice daily'],
    timings: ['With food'],
    sideEffects: ['Photosensitivity', 'Nausea', 'Esophagitis'],
    contraindications: ['Pregnancy', 'Children under 8'],
    warnings: ['Take with plenty of water'],
    storageInstructions: 'Store below 25°C',
    pricePerUnit: 10,
    requiresPrescription: true
  },

  // Antacids/GI
  {
    name: 'Omeprazole',
    genericName: 'Omeprazole',
    category: 'Gastrointestinal',
    type: 'Capsule',
    strength: '20mg',
    manufacturer: 'AstraZeneca',
    composition: 'Omeprazole 20mg',
    commonDosages: ['10mg', '20mg', '40mg'],
    frequencies: ['Once daily', 'Twice daily'],
    timings: ['Before breakfast', 'Before meals'],
    sideEffects: ['Headache', 'Diarrhea', 'Nausea'],
    contraindications: ['Hypersensitivity'],
    warnings: ['Long-term use concerns'],
    storageInstructions: 'Store below 25°C',
    pricePerUnit: 8,
    requiresPrescription: true
  },
  {
    name: 'Pantoprazole',
    genericName: 'Pantoprazole',
    category: 'Gastrointestinal',
    type: 'Tablet',
    strength: '40mg',
    manufacturer: 'Wyeth',
    composition: 'Pantoprazole sodium 40mg',
    commonDosages: ['20mg', '40mg'],
    frequencies: ['Once daily', 'Twice daily'],
    timings: ['Before breakfast'],
    sideEffects: ['Headache', 'Diarrhea', 'Flatulence'],
    contraindications: ['Hypersensitivity'],
    warnings: ['Long-term use may affect B12'],
    storageInstructions: 'Store below 25°C',
    pricePerUnit: 10,
    requiresPrescription: true
  },
  {
    name: 'Ranitidine',
    genericName: 'Ranitidine',
    category: 'Gastrointestinal',
    type: 'Tablet',
    strength: '150mg',
    manufacturer: 'GSK',
    composition: 'Ranitidine hydrochloride 150mg',
    commonDosages: ['150mg', '300mg'],
    frequencies: ['Twice daily', 'Once daily at bedtime'],
    timings: ['Before meals', 'At bedtime'],
    sideEffects: ['Headache', 'Constipation'],
    contraindications: ['Hypersensitivity'],
    warnings: ['May mask gastric cancer'],
    storageInstructions: 'Store below 25°C',
    pricePerUnit: 5,
    requiresPrescription: false
  },
  {
    name: 'Domperidone',
    genericName: 'Domperidone',
    category: 'Gastrointestinal',
    type: 'Tablet',
    strength: '10mg',
    manufacturer: 'Janssen',
    composition: 'Domperidone maleate 10mg',
    commonDosages: ['10mg'],
    frequencies: ['Three times daily'],
    timings: ['Before meals'],
    sideEffects: ['Dry mouth', 'Headache'],
    contraindications: ['GI bleeding', 'Prolactinoma'],
    warnings: ['Cardiac risk in elderly'],
    storageInstructions: 'Store below 25°C',
    pricePerUnit: 4,
    requiresPrescription: true
  },
  {
    name: 'Ondansetron',
    genericName: 'Ondansetron',
    category: 'Gastrointestinal',
    type: 'Tablet',
    strength: '4mg',
    manufacturer: 'GSK',
    composition: 'Ondansetron hydrochloride 4mg',
    commonDosages: ['4mg', '8mg'],
    frequencies: ['Every 8 hours', 'Twice daily', 'As needed'],
    timings: ['Before meals'],
    sideEffects: ['Headache', 'Constipation'],
    contraindications: ['QT prolongation'],
    warnings: ['ECG monitoring in some patients'],
    storageInstructions: 'Store below 25°C',
    pricePerUnit: 15,
    requiresPrescription: true
  },

  // Antihistamines
  {
    name: 'Cetirizine',
    genericName: 'Cetirizine',
    category: 'Antihistamine',
    type: 'Tablet',
    strength: '10mg',
    manufacturer: 'UCB Pharma',
    composition: 'Cetirizine hydrochloride 10mg',
    commonDosages: ['5mg', '10mg'],
    frequencies: ['Once daily'],
    timings: ['Evening', 'At bedtime'],
    sideEffects: ['Drowsiness', 'Dry mouth'],
    contraindications: ['Severe renal impairment'],
    warnings: ['May cause drowsiness'],
    storageInstructions: 'Store below 25°C',
    pricePerUnit: 3,
    requiresPrescription: false
  },
  {
    name: 'Loratadine',
    genericName: 'Loratadine',
    category: 'Antihistamine',
    type: 'Tablet',
    strength: '10mg',
    manufacturer: 'Schering-Plough',
    composition: 'Loratadine 10mg',
    commonDosages: ['10mg'],
    frequencies: ['Once daily'],
    timings: ['Morning', 'Evening'],
    sideEffects: ['Headache', 'Fatigue'],
    contraindications: ['Hypersensitivity'],
    warnings: ['Non-sedating antihistamine'],
    storageInstructions: 'Store below 25°C',
    pricePerUnit: 5,
    requiresPrescription: false
  },
  {
    name: 'Fexofenadine',
    genericName: 'Fexofenadine',
    category: 'Antihistamine',
    type: 'Tablet',
    strength: '120mg',
    manufacturer: 'Sanofi',
    composition: 'Fexofenadine hydrochloride 120mg',
    commonDosages: ['60mg', '120mg', '180mg'],
    frequencies: ['Once daily', 'Twice daily'],
    timings: ['Morning'],
    sideEffects: ['Headache', 'Nausea'],
    contraindications: ['Hypersensitivity'],
    warnings: ['Avoid fruit juice'],
    storageInstructions: 'Store below 25°C',
    pricePerUnit: 8,
    requiresPrescription: false
  },
  {
    name: 'Chlorpheniramine',
    genericName: 'Chlorpheniramine maleate',
    category: 'Antihistamine',
    type: 'Tablet',
    strength: '4mg',
    manufacturer: 'Generic Pharma',
    composition: 'Chlorpheniramine maleate 4mg',
    commonDosages: ['4mg'],
    frequencies: ['Every 4-6 hours', 'Three times daily'],
    timings: ['As needed'],
    sideEffects: ['Drowsiness', 'Dry mouth', 'Blurred vision'],
    contraindications: ['Glaucoma', 'Urinary retention'],
    warnings: ['Causes drowsiness'],
    storageInstructions: 'Store below 25°C',
    pricePerUnit: 2,
    requiresPrescription: false
  },

  // Cardiovascular
  {
    name: 'Amlodipine',
    genericName: 'Amlodipine',
    category: 'Antihypertensive',
    type: 'Tablet',
    strength: '5mg',
    manufacturer: 'Pfizer',
    composition: 'Amlodipine besylate 5mg',
    commonDosages: ['2.5mg', '5mg', '10mg'],
    frequencies: ['Once daily'],
    timings: ['Morning'],
    sideEffects: ['Ankle swelling', 'Headache', 'Flushing'],
    contraindications: ['Severe aortic stenosis'],
    warnings: ['Gradual dose adjustment'],
    storageInstructions: 'Store below 25°C',
    pricePerUnit: 5,
    requiresPrescription: true
  },
  {
    name: 'Losartan',
    genericName: 'Losartan potassium',
    category: 'Antihypertensive',
    type: 'Tablet',
    strength: '50mg',
    manufacturer: 'Merck',
    composition: 'Losartan potassium 50mg',
    commonDosages: ['25mg', '50mg', '100mg'],
    frequencies: ['Once daily'],
    timings: ['Morning'],
    sideEffects: ['Dizziness', 'Fatigue', 'Hyperkalemia'],
    contraindications: ['Pregnancy', 'Bilateral renal artery stenosis'],
    warnings: ['Monitor potassium'],
    storageInstructions: 'Store below 25°C',
    pricePerUnit: 8,
    requiresPrescription: true
  },
  {
    name: 'Atenolol',
    genericName: 'Atenolol',
    category: 'Cardiovascular',
    type: 'Tablet',
    strength: '50mg',
    manufacturer: 'AstraZeneca',
    composition: 'Atenolol 50mg',
    commonDosages: ['25mg', '50mg', '100mg'],
    frequencies: ['Once daily'],
    timings: ['Morning'],
    sideEffects: ['Fatigue', 'Cold extremities', 'Bradycardia'],
    contraindications: ['Asthma', 'Heart block'],
    warnings: ['Do not stop abruptly'],
    storageInstructions: 'Store below 25°C',
    pricePerUnit: 4,
    requiresPrescription: true
  },
  {
    name: 'Metoprolol',
    genericName: 'Metoprolol tartrate',
    category: 'Cardiovascular',
    type: 'Tablet',
    strength: '50mg',
    manufacturer: 'AstraZeneca',
    composition: 'Metoprolol tartrate 50mg',
    commonDosages: ['25mg', '50mg', '100mg'],
    frequencies: ['Twice daily'],
    timings: ['With meals'],
    sideEffects: ['Fatigue', 'Dizziness', 'Bradycardia'],
    contraindications: ['Severe bradycardia', 'Heart block'],
    warnings: ['Gradual withdrawal'],
    storageInstructions: 'Store below 25°C',
    pricePerUnit: 6,
    requiresPrescription: true
  },
  {
    name: 'Enalapril',
    genericName: 'Enalapril maleate',
    category: 'Antihypertensive',
    type: 'Tablet',
    strength: '5mg',
    manufacturer: 'Merck',
    composition: 'Enalapril maleate 5mg',
    commonDosages: ['2.5mg', '5mg', '10mg', '20mg'],
    frequencies: ['Once daily', 'Twice daily'],
    timings: ['Morning'],
    sideEffects: ['Dry cough', 'Dizziness', 'Hyperkalemia'],
    contraindications: ['Pregnancy', 'Angioedema history'],
    warnings: ['Monitor renal function'],
    storageInstructions: 'Store below 25°C',
    pricePerUnit: 5,
    requiresPrescription: true
  },
  {
    name: 'Hydrochlorothiazide',
    genericName: 'Hydrochlorothiazide',
    category: 'Cardiovascular',
    type: 'Tablet',
    strength: '25mg',
    manufacturer: 'Merck',
    composition: 'Hydrochlorothiazide 25mg',
    commonDosages: ['12.5mg', '25mg', '50mg'],
    frequencies: ['Once daily'],
    timings: ['Morning'],
    sideEffects: ['Electrolyte imbalance', 'Dizziness'],
    contraindications: ['Anuria', 'Sulfonamide allergy'],
    warnings: ['Monitor electrolytes'],
    storageInstructions: 'Store below 25°C',
    pricePerUnit: 3,
    requiresPrescription: true
  },

  // Antidiabetic
  {
    name: 'Metformin',
    genericName: 'Metformin hydrochloride',
    category: 'Antidiabetic',
    type: 'Tablet',
    strength: '500mg',
    manufacturer: 'Merck',
    composition: 'Metformin hydrochloride 500mg',
    commonDosages: ['500mg', '850mg', '1000mg'],
    frequencies: ['Twice daily', 'Three times daily'],
    timings: ['With meals'],
    sideEffects: ['GI upset', 'Lactic acidosis (rare)'],
    contraindications: ['Renal impairment', 'Contrast procedures'],
    warnings: ['Hold before contrast studies'],
    storageInstructions: 'Store below 25°C',
    pricePerUnit: 3,
    requiresPrescription: true
  },
  {
    name: 'Glimepiride',
    genericName: 'Glimepiride',
    category: 'Antidiabetic',
    type: 'Tablet',
    strength: '2mg',
    manufacturer: 'Sanofi',
    composition: 'Glimepiride 2mg',
    commonDosages: ['1mg', '2mg', '4mg'],
    frequencies: ['Once daily'],
    timings: ['With breakfast'],
    sideEffects: ['Hypoglycemia', 'Weight gain'],
    contraindications: ['Type 1 diabetes', 'DKA'],
    warnings: ['Risk of hypoglycemia'],
    storageInstructions: 'Store below 25°C',
    pricePerUnit: 5,
    requiresPrescription: true
  },
  {
    name: 'Sitagliptin',
    genericName: 'Sitagliptin phosphate',
    category: 'Antidiabetic',
    type: 'Tablet',
    strength: '100mg',
    manufacturer: 'Merck',
    composition: 'Sitagliptin phosphate 100mg',
    commonDosages: ['25mg', '50mg', '100mg'],
    frequencies: ['Once daily'],
    timings: ['Morning'],
    sideEffects: ['Upper respiratory infection', 'Headache'],
    contraindications: ['Hypersensitivity'],
    warnings: ['Pancreatitis risk'],
    storageInstructions: 'Store below 25°C',
    pricePerUnit: 25,
    requiresPrescription: true
  },

  // Vitamins/Supplements
  {
    name: 'Vitamin D3',
    genericName: 'Cholecalciferol',
    category: 'Vitamin',
    type: 'Tablet',
    strength: '60000IU',
    manufacturer: 'Generic Pharma',
    composition: 'Cholecalciferol 60000IU',
    commonDosages: ['1000IU', '2000IU', '60000IU'],
    frequencies: ['Once weekly', 'Once daily'],
    timings: ['With meals'],
    sideEffects: ['Hypercalcemia with overdose'],
    contraindications: ['Hypercalcemia'],
    warnings: ['Monitor calcium levels'],
    storageInstructions: 'Store below 25°C',
    pricePerUnit: 15,
    requiresPrescription: false
  },
  {
    name: 'Vitamin B Complex',
    genericName: 'Vitamin B Complex',
    category: 'Vitamin',
    type: 'Tablet',
    strength: 'Standard',
    manufacturer: 'Generic Pharma',
    composition: 'B1, B2, B3, B5, B6, B7, B9, B12',
    commonDosages: ['1 tablet'],
    frequencies: ['Once daily'],
    timings: ['After breakfast'],
    sideEffects: ['Yellow urine', 'Mild nausea'],
    contraindications: ['Hypersensitivity'],
    warnings: ['None significant'],
    storageInstructions: 'Store below 25°C',
    pricePerUnit: 2,
    requiresPrescription: false
  },
  {
    name: 'Ferrous Sulfate',
    genericName: 'Ferrous sulfate',
    category: 'Vitamin',
    type: 'Tablet',
    strength: '200mg',
    manufacturer: 'Generic Pharma',
    composition: 'Ferrous sulfate 200mg (65mg elemental iron)',
    commonDosages: ['200mg'],
    frequencies: ['Once daily', 'Twice daily'],
    timings: ['Empty stomach', 'With vitamin C'],
    sideEffects: ['Constipation', 'Dark stools', 'Nausea'],
    contraindications: ['Hemochromatosis'],
    warnings: ['Take with vitamin C for better absorption'],
    storageInstructions: 'Store below 25°C',
    pricePerUnit: 2,
    requiresPrescription: false
  },
  {
    name: 'Folic Acid',
    genericName: 'Folic acid',
    category: 'Vitamin',
    type: 'Tablet',
    strength: '5mg',
    manufacturer: 'Generic Pharma',
    composition: 'Folic acid 5mg',
    commonDosages: ['400mcg', '1mg', '5mg'],
    frequencies: ['Once daily'],
    timings: ['Morning'],
    sideEffects: ['Rare allergic reactions'],
    contraindications: ['Undiagnosed B12 deficiency'],
    warnings: ['May mask B12 deficiency'],
    storageInstructions: 'Store below 25°C',
    pricePerUnit: 2,
    requiresPrescription: false
  },
  {
    name: 'Calcium + Vitamin D',
    genericName: 'Calcium carbonate with Vitamin D3',
    category: 'Vitamin',
    type: 'Tablet',
    strength: '500mg + 250IU',
    manufacturer: 'Generic Pharma',
    composition: 'Calcium carbonate 500mg, Cholecalciferol 250IU',
    commonDosages: ['500mg + 250IU'],
    frequencies: ['Twice daily'],
    timings: ['With meals'],
    sideEffects: ['Constipation', 'Bloating'],
    contraindications: ['Hypercalcemia', 'Kidney stones'],
    warnings: ['Separate from other medications'],
    storageInstructions: 'Store below 25°C',
    pricePerUnit: 5,
    requiresPrescription: false
  },

  // Respiratory/Cough & Cold
  {
    name: 'Salbutamol',
    genericName: 'Salbutamol',
    category: 'Respiratory',
    type: 'Inhaler',
    strength: '100mcg',
    manufacturer: 'GSK',
    composition: 'Salbutamol sulfate 100mcg/puff',
    commonDosages: ['1-2 puffs'],
    frequencies: ['Every 4-6 hours', 'As needed'],
    timings: ['As needed'],
    sideEffects: ['Tremor', 'Palpitations', 'Headache'],
    contraindications: ['Hypersensitivity'],
    warnings: ['Overuse may indicate poor control'],
    storageInstructions: 'Store below 30°C',
    pricePerUnit: 150,
    requiresPrescription: true
  },
  {
    name: 'Montelukast',
    genericName: 'Montelukast sodium',
    category: 'Respiratory',
    type: 'Tablet',
    strength: '10mg',
    manufacturer: 'Merck',
    composition: 'Montelukast sodium 10mg',
    commonDosages: ['4mg', '5mg', '10mg'],
    frequencies: ['Once daily'],
    timings: ['Evening'],
    sideEffects: ['Headache', 'Abdominal pain'],
    contraindications: ['Hypersensitivity'],
    warnings: ['Neuropsychiatric events'],
    storageInstructions: 'Store below 25°C',
    pricePerUnit: 12,
    requiresPrescription: true
  },
  {
    name: 'Dextromethorphan',
    genericName: 'Dextromethorphan hydrobromide',
    category: 'Cough & Cold',
    type: 'Syrup',
    strength: '10mg/5ml',
    manufacturer: 'Generic Pharma',
    composition: 'Dextromethorphan HBr 10mg/5ml',
    commonDosages: ['5ml', '10ml'],
    frequencies: ['Every 4-6 hours', 'Three times daily'],
    timings: ['As needed'],
    sideEffects: ['Drowsiness', 'Dizziness'],
    contraindications: ['MAO inhibitors'],
    warnings: ['Do not use with MAOIs'],
    storageInstructions: 'Store below 25°C',
    pricePerUnit: 50,
    requiresPrescription: false
  },
  {
    name: 'Ambroxol',
    genericName: 'Ambroxol hydrochloride',
    category: 'Cough & Cold',
    type: 'Syrup',
    strength: '30mg/5ml',
    manufacturer: 'Boehringer',
    composition: 'Ambroxol hydrochloride 30mg/5ml',
    commonDosages: ['5ml', '10ml'],
    frequencies: ['Three times daily', 'Twice daily'],
    timings: ['After meals'],
    sideEffects: ['Nausea', 'GI upset'],
    contraindications: ['Hypersensitivity'],
    warnings: ['Adequate fluid intake recommended'],
    storageInstructions: 'Store below 25°C',
    pricePerUnit: 60,
    requiresPrescription: false
  },

  // Steroids
  {
    name: 'Prednisolone',
    genericName: 'Prednisolone',
    category: 'Steroid',
    type: 'Tablet',
    strength: '5mg',
    manufacturer: 'Generic Pharma',
    composition: 'Prednisolone 5mg',
    commonDosages: ['5mg', '10mg', '20mg', '40mg'],
    frequencies: ['Once daily', 'Twice daily'],
    timings: ['After breakfast', 'With meals'],
    sideEffects: ['Weight gain', 'Hyperglycemia', 'Insomnia'],
    contraindications: ['Systemic fungal infections'],
    warnings: ['Do not stop abruptly', 'Immunosuppression'],
    storageInstructions: 'Store below 25°C',
    pricePerUnit: 3,
    requiresPrescription: true
  },
  {
    name: 'Dexamethasone',
    genericName: 'Dexamethasone',
    category: 'Steroid',
    type: 'Tablet',
    strength: '0.5mg',
    manufacturer: 'Generic Pharma',
    composition: 'Dexamethasone 0.5mg',
    commonDosages: ['0.5mg', '4mg', '8mg'],
    frequencies: ['Once daily', 'As directed'],
    timings: ['Morning'],
    sideEffects: ['Hyperglycemia', 'Mood changes'],
    contraindications: ['Systemic infections'],
    warnings: ['Gradual tapering required'],
    storageInstructions: 'Store below 25°C',
    pricePerUnit: 4,
    requiresPrescription: true
  },

  // Antidepressants/Antianxiety
  {
    name: 'Sertraline',
    genericName: 'Sertraline hydrochloride',
    category: 'Antidepressant',
    type: 'Tablet',
    strength: '50mg',
    manufacturer: 'Pfizer',
    composition: 'Sertraline hydrochloride 50mg',
    commonDosages: ['25mg', '50mg', '100mg'],
    frequencies: ['Once daily'],
    timings: ['Morning', 'Evening'],
    sideEffects: ['Nausea', 'Insomnia', 'Sexual dysfunction'],
    contraindications: ['MAO inhibitors'],
    warnings: ['Suicidal ideation in young adults'],
    storageInstructions: 'Store below 25°C',
    pricePerUnit: 15,
    requiresPrescription: true
  },
  {
    name: 'Escitalopram',
    genericName: 'Escitalopram oxalate',
    category: 'Antidepressant',
    type: 'Tablet',
    strength: '10mg',
    manufacturer: 'Lundbeck',
    composition: 'Escitalopram oxalate 10mg',
    commonDosages: ['5mg', '10mg', '20mg'],
    frequencies: ['Once daily'],
    timings: ['Morning', 'Evening'],
    sideEffects: ['Nausea', 'Headache', 'Sleep changes'],
    contraindications: ['MAO inhibitors', 'QT prolongation'],
    warnings: ['Monitor for suicidality'],
    storageInstructions: 'Store below 25°C',
    pricePerUnit: 12,
    requiresPrescription: true
  },
  {
    name: 'Alprazolam',
    genericName: 'Alprazolam',
    category: 'Antianxiety',
    type: 'Tablet',
    strength: '0.5mg',
    manufacturer: 'Pfizer',
    composition: 'Alprazolam 0.5mg',
    commonDosages: ['0.25mg', '0.5mg', '1mg'],
    frequencies: ['Two to three times daily', 'As needed'],
    timings: ['As directed'],
    sideEffects: ['Drowsiness', 'Dependence', 'Memory impairment'],
    contraindications: ['Severe respiratory depression'],
    warnings: ['Risk of dependence', 'Avoid alcohol'],
    storageInstructions: 'Store below 25°C',
    pricePerUnit: 8,
    requiresPrescription: true
  },

  // Dermatological
  {
    name: 'Clotrimazole',
    genericName: 'Clotrimazole',
    category: 'Antifungal',
    type: 'Cream',
    strength: '1%',
    manufacturer: 'Bayer',
    composition: 'Clotrimazole 1% w/w',
    commonDosages: ['Apply thin layer'],
    frequencies: ['Twice daily', 'Three times daily'],
    timings: ['After cleaning affected area'],
    sideEffects: ['Local irritation', 'Burning sensation'],
    contraindications: ['Hypersensitivity'],
    warnings: ['For external use only'],
    storageInstructions: 'Store below 25°C',
    pricePerUnit: 45,
    requiresPrescription: false
  },
  {
    name: 'Fluconazole',
    genericName: 'Fluconazole',
    category: 'Antifungal',
    type: 'Tablet',
    strength: '150mg',
    manufacturer: 'Pfizer',
    composition: 'Fluconazole 150mg',
    commonDosages: ['50mg', '150mg', '200mg'],
    frequencies: ['Once daily', 'Once weekly', 'Single dose'],
    timings: ['With or without food'],
    sideEffects: ['Nausea', 'Headache', 'Abdominal pain'],
    contraindications: ['Hypersensitivity', 'Concomitant terfenadine'],
    warnings: ['Drug interactions'],
    storageInstructions: 'Store below 25°C',
    pricePerUnit: 30,
    requiresPrescription: true
  },
  {
    name: 'Betamethasone',
    genericName: 'Betamethasone valerate',
    category: 'Dermatological',
    type: 'Cream',
    strength: '0.1%',
    manufacturer: 'GSK',
    composition: 'Betamethasone valerate 0.1% w/w',
    commonDosages: ['Apply thin layer'],
    frequencies: ['Twice daily', 'Once daily'],
    timings: ['Morning and evening'],
    sideEffects: ['Skin thinning', 'Burning', 'Stretch marks'],
    contraindications: ['Skin infections', 'Rosacea'],
    warnings: ['Not for prolonged use', 'Avoid face'],
    storageInstructions: 'Store below 25°C',
    pricePerUnit: 55,
    requiresPrescription: true
  },
  {
    name: 'Mupirocin',
    genericName: 'Mupirocin',
    category: 'Dermatological',
    type: 'Ointment',
    strength: '2%',
    manufacturer: 'GSK',
    composition: 'Mupirocin 2% w/w',
    commonDosages: ['Apply thin layer'],
    frequencies: ['Three times daily'],
    timings: ['After cleaning wound'],
    sideEffects: ['Burning', 'Stinging', 'Itching'],
    contraindications: ['Hypersensitivity'],
    warnings: ['For topical use only'],
    storageInstructions: 'Store below 25°C',
    pricePerUnit: 75,
    requiresPrescription: true
  },

  // Eye/Ophthalmic
  {
    name: 'Ciprofloxacin Eye Drops',
    genericName: 'Ciprofloxacin',
    category: 'Ophthalmic',
    type: 'Drops',
    strength: '0.3%',
    manufacturer: 'Alcon',
    composition: 'Ciprofloxacin hydrochloride 0.3%',
    commonDosages: ['1-2 drops'],
    frequencies: ['Every 2 hours initially', 'Four times daily'],
    timings: ['As directed'],
    sideEffects: ['Burning', 'Itching', 'White deposits'],
    contraindications: ['Hypersensitivity'],
    warnings: ['Remove contact lenses'],
    storageInstructions: 'Store below 25°C',
    pricePerUnit: 60,
    requiresPrescription: true
  },
  {
    name: 'Artificial Tears',
    genericName: 'Carboxymethylcellulose sodium',
    category: 'Ophthalmic',
    type: 'Drops',
    strength: '0.5%',
    manufacturer: 'Allergan',
    composition: 'Carboxymethylcellulose sodium 0.5%',
    commonDosages: ['1-2 drops'],
    frequencies: ['As needed', 'Four to six times daily'],
    timings: ['As needed'],
    sideEffects: ['Temporary blurred vision'],
    contraindications: ['Hypersensitivity'],
    warnings: ['Do not touch dropper tip'],
    storageInstructions: 'Store below 25°C',
    pricePerUnit: 80,
    requiresPrescription: false
  },

  // Antipyretic
  {
    name: 'Paracetamol Syrup',
    genericName: 'Acetaminophen',
    category: 'Antipyretic',
    type: 'Syrup',
    strength: '120mg/5ml',
    manufacturer: 'Generic Pharma',
    composition: 'Paracetamol 120mg/5ml',
    commonDosages: ['2.5ml', '5ml', '10ml'],
    frequencies: ['Every 4-6 hours', 'As needed'],
    timings: ['As needed'],
    sideEffects: ['Rare allergic reactions'],
    contraindications: ['Liver disease'],
    warnings: ['Do not exceed recommended dose'],
    storageInstructions: 'Store below 25°C',
    pricePerUnit: 35,
    requiresPrescription: false
  },

  // Additional commonly used medicines
  {
    name: 'Tramadol',
    genericName: 'Tramadol hydrochloride',
    category: 'Analgesic',
    type: 'Tablet',
    strength: '50mg',
    manufacturer: 'Grunenthal',
    composition: 'Tramadol hydrochloride 50mg',
    commonDosages: ['50mg', '100mg'],
    frequencies: ['Every 4-6 hours', 'Three times daily'],
    timings: ['With or without food'],
    sideEffects: ['Nausea', 'Dizziness', 'Constipation'],
    contraindications: ['Seizure disorders', 'MAO inhibitors'],
    warnings: ['Risk of dependence'],
    storageInstructions: 'Store below 25°C',
    pricePerUnit: 10,
    requiresPrescription: true
  },
  {
    name: 'Loperamide',
    genericName: 'Loperamide hydrochloride',
    category: 'Gastrointestinal',
    type: 'Capsule',
    strength: '2mg',
    manufacturer: 'Johnson & Johnson',
    composition: 'Loperamide hydrochloride 2mg',
    commonDosages: ['2mg', '4mg'],
    frequencies: ['After each loose stool', 'As needed'],
    timings: ['As needed'],
    sideEffects: ['Constipation', 'Abdominal cramps'],
    contraindications: ['Bloody diarrhea', 'Bacterial enterocolitis'],
    warnings: ['Not for infectious diarrhea'],
    storageInstructions: 'Store below 25°C',
    pricePerUnit: 5,
    requiresPrescription: false
  },
  {
    name: 'ORS (Oral Rehydration Salt)',
    genericName: 'Oral Rehydration Salts',
    category: 'Gastrointestinal',
    type: 'Powder',
    strength: 'Standard WHO formula',
    manufacturer: 'WHO/Generic',
    composition: 'Sodium chloride, Potassium chloride, Sodium citrate, Glucose',
    commonDosages: ['1 sachet in 1L water'],
    frequencies: ['As needed', 'After each loose stool'],
    timings: ['As needed'],
    sideEffects: ['Vomiting if taken too fast'],
    contraindications: ['Bowel obstruction'],
    warnings: ['Use fresh solution within 24 hours'],
    storageInstructions: 'Store below 25°C',
    pricePerUnit: 5,
    requiresPrescription: false
  },
  {
    name: 'Insulin Regular',
    genericName: 'Human Insulin Regular',
    category: 'Antidiabetic',
    type: 'Injection',
    strength: '100IU/ml',
    manufacturer: 'Novo Nordisk',
    composition: 'Human insulin (rDNA origin) 100IU/ml',
    commonDosages: ['As per blood glucose'],
    frequencies: ['Before meals', 'As directed'],
    timings: ['30 minutes before meals'],
    sideEffects: ['Hypoglycemia', 'Injection site reactions'],
    contraindications: ['Hypoglycemia'],
    warnings: ['Monitor blood glucose regularly'],
    storageInstructions: 'Store at 2-8°C, do not freeze',
    pricePerUnit: 250,
    requiresPrescription: true
  },
  {
    name: 'Levothyroxine',
    genericName: 'Levothyroxine sodium',
    category: 'Other',
    type: 'Tablet',
    strength: '50mcg',
    manufacturer: 'Abbott',
    composition: 'Levothyroxine sodium 50mcg',
    commonDosages: ['25mcg', '50mcg', '75mcg', '100mcg'],
    frequencies: ['Once daily'],
    timings: ['Empty stomach', 'Morning'],
    sideEffects: ['Palpitations', 'Weight loss', 'Insomnia'],
    contraindications: ['Untreated adrenal insufficiency', 'Thyrotoxicosis'],
    warnings: ['Take 30-60 min before breakfast'],
    storageInstructions: 'Store below 25°C',
    pricePerUnit: 8,
    requiresPrescription: true
  }
];

const seedMedicines = async () => {
  try {
    const mongoUri = process.env.MONGO_URI || 'mongodb://localhost:27017/crafton';
    await mongoose.connect(mongoUri);
    console.log('Connected to MongoDB');

    // Clear existing medicines
    await Medicine.deleteMany({});
    console.log('Cleared existing medicines');

    // Insert new medicines
    const result = await Medicine.insertMany(medicines);
    console.log(`Successfully seeded ${result.length} medicines`);

    await mongoose.connection.close();
    console.log('Database connection closed');
    process.exit(0);
  } catch (error) {
    console.error('Error seeding medicines:', error);
    process.exit(1);
  }
};

// Run if called directly
if (require.main === module) {
  seedMedicines();
}

module.exports = { medicines, seedMedicines };
